"""empty message

Revision ID: 1e5a50177c1b
Revises: 5e4e76f7b42c
Create Date: 2022-05-17 17:12:28.134349

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1e5a50177c1b'
down_revision = '5e4e76f7b42c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('registros', 'contrasena')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('registros', sa.Column('contrasena', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
