"""empty message

Revision ID: 2e0dab929a6f
Revises: 43a7c4b494ff
Create Date: 2022-05-17 17:05:06.984393

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2e0dab929a6f'
down_revision = '43a7c4b494ff'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('registros', 'nombres',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.alter_column('registros', 'contrasena',
               existing_type=sa.VARCHAR(length=250),
               nullable=False)           
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('registros', 'nombres',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    # ### end Alembic commands ###
