"""empty message

Revision ID: 43a7c4b494ff
Revises: cc77533c7b0b
Create Date: 2022-05-17 16:34:06.919844

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '43a7c4b494ff'
down_revision = 'cc77533c7b0b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('registros', 'nombres',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.alter_column('registros', 'apellidos',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.alter_column('registros', 'correo',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.alter_column('registros', 'contrasena',
               existing_type=sa.VARCHAR(length=250),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('registros', 'contrasena',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.alter_column('registros', 'correo',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.alter_column('registros', 'apellidos',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.alter_column('registros', 'nombres',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    # ### end Alembic commands ###
