"""empty message

Revision ID: 60fe93b1cf14
Revises: 0d45eaa5f4de
Create Date: 2022-05-17 20:02:00.964592

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '60fe93b1cf14'
down_revision = '0d45eaa5f4de'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('catalogos', 'complet')
    op.drop_column('catalogos', 'cantidad')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('catalogos', sa.Column('cantidad', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('catalogos', sa.Column('complet', sa.BOOLEAN(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
