"""empty message

Revision ID: 769dd873dff8
Revises: ff821c80315d
Create Date: 2022-05-16 22:17:14.874425

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '769dd873dff8'
down_revision = 'ff821c80315d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categorias',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre_categoria', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('categorias')
    # ### end Alembic commands ###
