"""empty message

Revision ID: ff821c80315d
Revises: 
Create Date: 2022-05-16 20:31:07.241670

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ff821c80315d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('catalogos', sa.Column('complet', sa.Boolean(), nullable=False))
    op.execute('UPDATE catalogos SET complet = False WHERE completed IS NULL;')
    op.alter_column('todos', 'complet', nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('catalogos', 'complet')
    # ### end Alembic commands ###
